In [1]:
import numpy as np

In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### We can select individual arrays element by passing the comma seperated list

In [7]:
arr2d[1,0]

4

### Indexing with Slices 

In [8]:
arr = [ 0, 1, 2, 3, 4, 64, 64, 64, 8, 9]

In [14]:
arr[1:6]

[1, 2, 3, 4, 64]

### when we select `arr2d[:2]` i'ts like we are saying " select the first two rows of arr2d "

In [13]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

### We can pass mulptile slices 

In [17]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[:2,2:]

array([[3],
       [6]])

In [50]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

#### selecting Second Row , first 2 columns 

In [49]:
arr2d[1,:2]

array([4, 5])

#### Selecting third column , but only first two rows

In [57]:
arr2d[:2,2]


array([3, 6])

#### 

In [56]:
arr2d[:,0]

array([1, 4, 7])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[1,1]

5

In [67]:
arr2d[:2,1:] =0

In [68]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### fo